# Generated by Django 5.2.8 on 2025-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags (e.g., work, personal, urgent)",
                max_length=200,
            ),
        ),
    ]
